name = "Dungeon Heroes"
author = "maciello"
version = "1.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92512052486e1cc60b9f79c1c9f5eefe1b41ea046cd5fa8848b5504a8d502d6d"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
