name = "Dungeon Heroes"
author = "maciello"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91401dab557f581ac03a4d3ff4b72710653eaba2dc9bb9ec0a56e37b05d676f3"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
