name = "Dungeon Heroes"
author = "maciello"
version = "2.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9e9b989d8af18b7809484e8471447f0304d6396b974b4a4e16965f5bb7f7a52"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"
